name: WoolBattle
version: '1.0-SNAPSHOT'
main: net.thevace.woolBattle.WoolBattle
api-version: '1.21'
commands:
  joinQueue:
    description: joins a queue
    usage: /joinQueue
  startGame:
    description: start the woolbattle game
    usage: /startGame
  getQueue:
    description: get all queues or the queue a player is in
    usage: /getQueue <Player>
  getPlayerWool:
    description: get your wool
    usage: /getPlayerWool
depend: [InventoryFramework]

